Updated tilt to also support proc interface.
jvatic/react-jsx-sprockets pull request #4
Opened 2016-11-26 04:12 UTC by mikesmit

As of the latest version of sprockets tilt is deprecated.
http://edgeguides.rubyonrails.org/asset_pipeline.html#making-your-library-or-gem-a-pre-processor

This change updates the Tilt object to also support call so it will work with the non-tilt version of sprockets.

2016-11-29 15:16 UTC, jvatic requested changes
LGTM pending minor comments

2016-11-29 15:16 UTC, jvatic commented on lib/react-jsx-sprockets/tilt.rb
> +      self.call({data:data})
No need for the `{}`, can be simplified to `self.call(data: data)`.

2016-11-29 15:16 UTC, jvatic commented on lib/react-jsx-sprockets/tilt.rb
> +    def self.call input
Lets be consistent with use of `()` and change this to `def self.call(input)`.

2016-11-29 15:17 UTC, jvatic commented
It'd also be good if you can squash the commits

2016-12-02 04:31 UTC, mikesmit commented
Sure thing.

2016-12-02 11:19 UTC, jvatic approved these changes

2016-12-02 11:20 UTC, merged

2016-12-02 11:20 UTC, jvatic commented
Thanks!